### ISSUE TITLE
in version v0.54.1, there is a crash with the ae2fc mod

### ISSUE THREAD

**Issue by Xikaro** [PrototypeTrousers/Applied-Energistics-2#159]
in version v0.54.1, there is a crash with the ae2fc mod

java.lang.ExceptionInInitializerError
    at com.glodblock.github.util.Ae2ReflectClient.<clinit>(Ae2ReflectClient.java:45)
    at com.glodblock.github.client.model.DenseEncodedPatternModel.bake(DenseEncodedPatternModel.java:42)
    at net.minecraftforge.client.model.ModelLoader.setupModelRegistry(ModelLoader.java:180)
    at net.minecraft.client.renderer.block.model.ModelManager.onResourceManagerReload(ModelManager.java:28)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.registerReloadListener(SimpleReloadableResourceManager.java:121)
    at net.minecraft.client.Minecraft.init(Minecraft.java:513)
    at net.minecraft.client.Minecraft.run(Minecraft.java:6101)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalStateException: Failed to initialize AE2 reflection hacks!
    at com.glodblock.github.util.Ae2Reflect.<clinit>(Ae2Reflect.java:80)
    ... 14 more
Caused by: java.lang.NoSuchFieldException: Can't find field from [craftingSlots]
    at com.glodblock.github.util.Ae2Reflect.reflectField(Ae2Reflect.java:100)
    at com.glodblock.github.util.Ae2Reflect.<clinit>(Ae2Reflect.java:63)
    ... 14 more

- AE2 Version: v0.54.1
- Forge Version: 14.23.5.2860
- Minecraft 1.12.2
- Fluid Craft for AE2-2.4.1-r

**Comment by Exaxxion** [comment]
> Failed to initialize AE2 reflection hacks

Sounds like the problem is on AE2FC's side. This is what happens when you use reflection to force your way into a mod's code, then that mod's code changes.

**Comment by Xikaro** [comment]
https://www.curseforge.com/minecraft/mc-mods/ae2-fluid-crafting-rework/files/4035319
