### ISSUE TITLE
[0.54.20] Incompatibility with the up-to-date Inventory Bogo Sorter (1.2.2)

### ISSUE THREAD

**Issue by NeveHanter** [PrototypeTrousers/Applied-Energistics-2#216]
**Describe the bug**
AE2 crash after fiddling with the AE2 terminal sort order due to ABI incompatibility with up-to-date version of Inventory Bogo Sorter (1.2.2). The Bogo has changed it's code so the ITEM_COMPARATOR is no longer at the location AE2 is expecting it to be.
See: https://github.com/CleanroomMC/InventoryBogoSorter/commit/29b21444ad2dbdcddca6fc09e9f5de950087171d#diff-ba4d0448ffa9f7454316cd0a4c67832e1ee958fe0504706d753099a56ca44deaL203

**To Reproduce**
Change the sort order in AE2 terminal (couple of times, so it starts using Bogo) and have the world immediately crash and after loading back crash when you open the terminal.

**Expected behavior**
No crash and working sort with up-to-date Inventory Bogo Sorter or clear indication of no support between these two.

**Additional context**
Crash log: https://pastes.dev/ZUeaujQdGF
Excerpt with the exception:
```
---- Minecraft Crash Report ----
// Lolis deobfuscated this stacktrace using MCP's stable-39 mappings.
// I bet Cylons wouldn't have this problem.
Time: 2023-02-05 18:20:41 CET
Description: Ticking screen
java.lang.NoSuchFieldError: ITEM_COMPARATOR
    at appeng.integration.modules.bogosorter.InventoryBogoSortModule.lambda$static$0(InventoryBogoSortModule.java:12)
    at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
    at java.util.TimSort.sort(TimSort.java:234)
    at java.util.Arrays.sort(Arrays.java:1512)
    at java.util.ArrayList.sort(ArrayList.java:1464)
    at java.util.Collections.sort(Collections.java:177)
    at appeng.client.me.ItemRepo.updateView(ItemRepo.java:196)
    at appeng.client.gui.implementations.GuiMEMonitorable.updateScreen(GuiMEMonitorable.java:508)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1779)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:4114)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
    at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
    at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
    at org.polymc.EntryPoint.listen(EntryPoint.java:144)
    at org.polymc.EntryPoint.main(EntryPoint.java:74)
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Affected screen --
  Screen name: appeng.client.gui.implementations.GuiMEMonitorable
```

**Environment**
-

- Minecraft Version: 1.12.2
- AE2 Version: 0.54.19 / 0.54.20
- Forge Version: 14.23.5.2860

**Comment by skps00** [comment]
the new ver, can use both the same time, but while I using Inventory Bogo Sorter at the wireless crafting terminal, the item inside the inventory will disappear
