### ISSUE TITLE
Server crashed after player inserted Magnet Card into Wireless Terminal

### ISSUE THREAD

**Issue by 200542053** [PrototypeTrousers/Applied-Energistics-2#224]
**Describe the bug**
Server crashed after player inserted Magnet Card into Wireless Terminal.
(Inserting into the Wireless Crafting Terminal will not cause any problems)

When the server is restarted, the player is unable to join the server with the message "a fatal error has occurred, this connection is terminated".
After removing the Wireless Terminal from the player's inventory by NBTeditor, the player can join the server again.

Cannot be reproduced in single player mode.

**Environment**
- Server: CatServer-222f2a5f-universal
- Minecraft Version: 1.12.2

- AE2 Version: appliedenergistics2-rv6-stable-7-extended_life-v0.55.5
- Forge Version: 14.23.5.2860
[crash-2023-02-16_14.43.21-server.txt](https://github.com/PrototypeTrousers/Applied-Energistics-2/files/10773456/crash-2023-02-16_14.43.21-server.txt)

**Comment by PrototypeTrousers** [comment]
do you have the crash log ?

**Comment by LordofDorknes** [comment]
In my case, the server did not crash, but did generate a traceback and prevent the player from rejoining.
[15:09:45] [Server thread/WARN]: Failed to handle packet for /(IP ADDRESS)
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:459) ~[oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.update(NetHandlerPlayServer.java:173) ~[pa.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_351]
Caused by: java.lang.NoSuchMethodError: net.minecraft.util.math.AxisAlignedBB.<init>(Lnet/minecraft/util/math/Vec3d;Lnet/minecraft/util/math/Vec3d;)V
	at appeng.items.tools.powered.ToolWirelessTerminal.magnetLogic(ToolWirelessTerminal.java:212) ~[ToolWirelessTerminal.class:?]
	at appeng.items.tools.powered.ToolWirelessTerminal.onUpdate(ToolWirelessTerminal.java:161) ~[ToolWirelessTerminal.class:?]
	at net.minecraft.item.ItemStack.updateAnimation(ItemStack.java:526) ~[aip.class:?]
	at net.minecraft.entity.player.InventoryPlayer.decrementAnimations(InventoryPlayer.java:363) ~[aec.class:?]
	at net.minecraft.entity.player.EntityPlayer.onLivingUpdate(EntityPlayer.java:511) ~[aed.class:?]
	at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2179) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:234) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:382) ~[oq.class:?]
	... 9 more
[15:09:45] [Server thread/INFO]: (PLAYER) lost connection: Internal server error

**Comment by 200542053** [comment]
I just uploaded the crash report, I don't know why it didn't get uploaded before

**Comment by HungryDoctor** [comment]
Having the same issue

**Comment by PrototypeTrousers** [comment]
55.8 is up on CF now
