### ISSUE TITLE
AE-Additions mod incompatible 

### ISSUE THREAD

**Issue by zeng-github01** [PrototypeTrousers/Applied-Energistics-2#254]
**Describe the bug**
Can't open its Universal Wireless Terminal in Item Mode
**To Reproduce**

**Expected behavior**

**Additional context**

errorlog:
`Error executing task
java.util.concurrent.ExecutionException: java.lang.AbstractMethodError
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.AbstractMethodError
	at appeng.core.features.registries.WirelessRegistry.openWirelessTerminalGui(WirelessRegistry.java:101) ~[WirelessRegistry.class:?]
	at com.the9grounds.aeadditions.item.ItemWirelessTerminalUniversal.func_77659_a(ItemWirelessTerminalUniversal.kt:104) ~[ItemWirelessTerminalUniversal.class:?]
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217) ~[aip.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:358) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:765) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[mb.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[mb.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more`

**Environment**

- Minecraft Version: 
- AE2 Version: 
- Forge Version:

**Comment by zeng-github01** [comment]
I contributed a patch to AE-Additions myself that fixes this issue.
on my own GitHub repository
