### ISSUE TITLE
Wireless Terminal can't put blanck pattern on it by press Shift

### ISSUE THREAD

**Issue by zeng-github01** [PrototypeTrousers/Applied-Energistics-2#260]
**Describe the bug**

Wireless Terminal can't put blanck pattern on it by press Shift

**To Reproduce**

**Expected behavior**

**Additional context**
errorlog: 
` Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
        at appeng.container.implementations.ContainerPatternEncoder.func_82846_b(ContainerPatternEncoder.java:100) ~[ContainerPatternEncoder.class:?]
        at net.minecraft.inventory.Container.func_184996_a(Container.java:246) ~[afr.class:?]
        at appeng.container.implementations.ContainerWirelessPatternTerminal.func_184996_a(ContainerWirelessPatternTerminal.java:194) ~[ContainerWirelessPatternTerminal.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1162) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more`

**Environment**

- Minecraft Version: 
- AE2 Version: 
- Forge Version:

**Comment by zeng-github01** [comment]
this.getPart() method return NULL @PrototypeTrousers
