### ISSUE TITLE
`Server Crash` with `TileEnergyCell`

### ISSUE THREAD

**Issue by Coloryr** [PrototypeTrousers/Applied-Energistics-2#264]
```
---- Minecraft Crash Report ----
// Lolis deobfuscated this stacktrace using MCP's stable-39 mappings.
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2023-04-16 13:09:35 CST
Description: Exception ticking world

java.lang.IllegalStateException: Loading data after part of a grid, this is invalid.
    at appeng.me.GridNode.loadFromNBT(GridNode.java:272)
    at appeng.me.helpers.AENetworkProxy.readFromNBT(AENetworkProxy.java:137)
    at appeng.tile.grid.AENetworkTile.readFromNBT(AENetworkTile.java:40)
    at appeng.tile.networking.TileEnergyCell.readFromNBT(TileEnergyCell.java:100)
    at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockState.update(CraftBlockState.java:215)
    at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockState.update(CraftBlockState.java:177)
    at net.minecraft.block.BlockSapling.updateTick(BlockSapling.java:84)
    at net.minecraft.block.Block.randomTick(Block.java:508)
    at net.minecraft.world.WorldServer.updateBlocks(WorldServer.java:605)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:331)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:965)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:475)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:828)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:687)
    at java.lang.Thread.run(Thread.java:750)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
```

```
Minecraft Version: 1.12.2
  Operating System: Linux (amd64) version 5.14.0-162.23.1.el9_1.x86_64
  Java Version: 1.8.0_361, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1319693472 bytes (1258 MB) / 4601151488 bytes (4388 MB) up to 9857662976 bytes (9401 MB)
  JVM Flags: 7 total; -XX:+UseParallelGC -XX:ParallelGCThreads=6 -XX:MaxDirectMemorySize=336M -XX:MaxMetaspaceSize=732M -XX:CompressedClassSpaceSize=164M -XX:ReservedCodeCacheSize=480M -Xmx10576M
```

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-7-extended_life-v0.55.8
- Forge Version: 14.23.5.2860

**Comment by KorewaLidesu** [comment]
need full context
please provide debug.log

**Comment by Coloryr** [comment]
[debug-1.log](https://github.com/PrototypeTrousers/Applied-Energistics-2/files/11241298/debug-1.log)

**Comment by Coloryr** [comment]
Is may causing from `CensoredASM` ?

**Comment by KorewaLidesu** [comment]
> Is may causing from `CensoredASM` ?

You are running hybrid server, try ask on catserver first.
:worry:
