### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by lxy-unnamed** [PrototypeTrousers/Applied-Energistics-2#31]
```
java.lang.NullPointerException: Exception in server tick loop
        at appeng.helpers.DualityInterface.invIsBlockedGTCE(DualityInterface.java:1045)
        at appeng.helpers.DualityInterface.isGTCEblocked(DualityInterface.java:1217)
        at appeng.helpers.DualityInterface.isBusy(DualityInterface.java:1195)
        at appeng.me.cluster.implementations.CraftingCPUCluster.executeCrafting(CraftingCPUCluster.java:659)
        at appeng.me.cluster.implementations.CraftingCPUCluster.updateCraftingLogic(CraftingCPUCluster.java:610)
        at appeng.me.cache.CraftingGridCache.onUpdateTick(CraftingGridCache.java:154)
        at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:43)
        at appeng.me.Grid.update(Grid.java:284)
        at appeng.hooks.TickHandler.onTick(TickHandler.java:227)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1118_TickHandler_onTick_TickEvent.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:748)
```
Complete Crash Report:
[crash-2021-06-21_19.10.29-server.txt](https://github.com/PrototypeTrousers/Applied-Energistics-2/files/6687139/crash-2021-06-21_19.10.29-server.txt)

- Minecraft Version: 
- AE2 Version: appliedenergistics2-rv6-stable-7.omni-fixes-v41
- Forge Version: forge-1.12.2-14.23.5.2854

**Comment by PrototypeTrousers** [comment]
extra null checks were added after v41. hope it solves this one
