### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by zeng-github01** [PrototypeTrousers/Applied-Energistics-2#314]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional context**
java.lang.NullPointerException: Ticking block entity
    at appeng.block.misc.BlockLightDetector.func_180656_a(BlockLightDetector.java:84)
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185911_a(BlockStateContainer.java:388)
    at net.minecraft.world.World.func_175651_c(World.java:3271)
    at net.minecraft.world.World.func_175640_z(World.java:3298)
    at org.dave.bonsaitrees.tile.TileBonsaiPot.tryToCutAndExport(TileBonsaiPot.java:406)
    at org.dave.bonsaitrees.tile.TileBonsaiPot.checkProgress(TileBonsaiPot.java:455)
    at org.dave.bonsaitrees.tile.TileBonsaiPot.func_73660_a(TileBonsaiPot.java:471)
    at net.minecraft.world.World.func_72939_s(World.java:1838)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)

**Environment**

- Minecraft Version: 
- AE2 Version: 
- Forge Version:

**Comment by zeng-github01** [comment]
This is a compatibility issue with RS
