### ISSUE TITLE
Null Pointer Exception (with another mod)

### ISSUE THREAD

**Issue by Theoooooo** [PrototypeTrousers/Applied-Energistics-2#51]
Hello,

i've been playing omnifactory for a while now, and i added back in the days VolumetricFlask to simply automatize and simplify crafting with fluids.
But since i've updated to the last dev build, which include this fork of AE2, i'm getting NullPointerException anytime i just take something inside my ME Drives.

I know this mod is outdated and has been only made for a specific purpose, but the modification made to this AE2 fork may cause some issues, as well as the new interface expansion card (i think)

```java.lang.NullPointerException
    at me.exz.volumetricflask.common.helpers.DualityOInterface.pushPattern(DualityOInterface.java:139)
    at appeng.me.cluster.implementations.CraftingCPUCluster.executeCrafting(CraftingCPUCluster.java:831)
    at appeng.me.cluster.implementations.CraftingCPUCluster.updateCraftingLogic(CraftingCPUCluster.java:676)
    at appeng.me.cache.CraftingGridCache.onUpdateTick(CraftingGridCache.java:154)
    at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:43)
    at appeng.me.Grid.update(Grid.java:284)
    at appeng.hooks.TickHandler.onTick(TickHandler.java:222)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1040_TickHandler_onTick_TickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:712)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
```

I'm aware that this is not the intended way to use this mod (because it's not included inside the modpack) but maybe there is a fix around it because this mod is really really usefull ...

**Version :**
- appliedenergistics2-rv6-stable-7.omni-fixes-v46i
- volumetricflask-0.16 [Git repo of the mod](https://github.com/exzhawk/VolumetricFlask)

**Comment by Theoooooo** [comment]
Neat 👌
Is there a workflow to build a new .jar with the modifications or do i need to build it myself with a java compiler ?
