### ISSUE TITLE
Crash: LoaderExceptionModCrash NoClassDefFoundError: gregtech

### ISSUE THREAD

**Issue by Krutoy242** [PrototypeTrousers/Applied-Energistics-2#96]
Updating `50c` -> `51g` causing game to crash on load with this log:

```less
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from AE2 Unofficial Extended Life (appliedenergistics2)
Caused by: java.lang.NoClassDefFoundError: gregtech/api/items/metaitem/MetaItem
    at appeng.helpers.NonBlockingItems.<init>(NonBlockingItems.java:56)
    at appeng.helpers.NonBlockingItems.<clinit>(NonBlockingItems.java:21)
[...]
Caused by: java.lang.ClassNotFoundException: gregtech.api.items.metaitem.MetaItem
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
```
[crash-2022-03-30_20.34.56-client.txt](https://github.com/PrototypeTrousers/Applied-Energistics-2/files/8382894/crash-2022-03-30_20.34.56-client.txt)

Also, another issue still actual, please reopen it -> https://github.com/PrototypeTrousers/Applied-Energistics-2/issues/90. 
Older issue related to gregtech too, but happen on **world load**. Current issue happen on **game load**.

**Comment by PrototypeTrousers** [comment]
added another check to see if the gregtech mod is installed in v51h
if for some reason you cant upgrade the mod, delete the gregtech items from the NonBlockin list in the config file, that should avoid the crash
